name: Build Custom FFmpeg AAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: 28.2.13676358
      ANDROID_API: 29
      ARCH: arm64-v8a

    steps:
      # 1️⃣ Checkout your FFmpeg repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake git pkg-config yasm \
            autoconf automake libtool nasm \
            python3 python3-pip curl unzip \
            ninja-build meson gettext

      # 3️⃣ Download Android NDK
      - name: Download NDK
        run: |
          mkdir -p $HOME/android-ndk
          curl -L "https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip" -o ndk.zip
          unzip -q ndk.zip -d $HOME/android-ndk
          mv $HOME/android-ndk/android-ndk-${ANDROID_NDK_VERSION} $HOME/android-ndk/${ANDROID_NDK_VERSION}
          echo "$HOME/android-ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_PATH

      # 4️⃣ Set up executable permissions for script
      - name: Make android.sh executable
        run: chmod +x android.sh

      # 5️⃣ Run FFmpeg build script
      - name: Build FFmpeg
        run: ./android.sh

      # 6️⃣ Create minimal AAR structure
      - name: Package AAR
        run: |
          mkdir -p aar/jni/${ARCH}
          cp build/install/lib/libav*.a aar/jni/${ARCH}/
          cd aar
          zip -r ffmpeg-kit-custom.aar *

      # 7️⃣ Upload AAR artifact
      - name: Upload AAR
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-kit-custom.aar
          path: aar/ffmpeg-kit-custom.aar
