name: Build FFmpeg AAR for Android ARM64

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  # Adjust to the latest NDK and API levels as needed
  ANDROID_NDK_VERSION: "25.2.9519653"
  ANDROID_API_LEVEL: "29"
  ANDROID_ABI: "arm64-v8a"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git pkg-config autoconf automake libtool cmake yasm

      - name: Install Android SDK & NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          build-tools-version: "30.0.3"
          sdk-tools-version: "latest"
          components: |
            platform-tools

      - name: Verify NDK installation
        run: |
          echo "NDK root: $ANDROID_NDK_HOME"
          ls -l "$ANDROID_NDK_HOME"

      - name: Make android.sh executable
        run: chmod +x ./android.sh

      - name: Run Android build script
        run: |
          ./android.sh \
            --full \
            --enable-gpl \
            --api-level $ANDROID_API_LEVEL \
            --arch $ANDROID_ABI \
            --disable-arm-v7a \
            --disable-x86 --disable-x86_64 \
            --disable-doc \
            --disable-network --disable-devices --disable-debug \
            \
            # External video codecs:
            --enable-libx264 \
            --enable-libx265 \
            --enable-libvpx \
            --enable-libaom \
            \
            # External audio codecs:
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libvorbis \
            \
            # Subtitles & fonts:
            --enable-libass \
            --enable-libfreetype \
            --enable-libfribidi \
            \
            # Images:
            --enable-libwebp \
            \
            # Android-specific:
            --enable-android-media-codec \
            --enable-zlib

      - name: Upload built AAR
          uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-arm64-aar
          path: |
            android-libs/android-arm64-v8a-release.aar
            # adjust path if your script places it elsewhere
